name: Setup
description: Install Bun and dependencies

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: '.bun-version'

    - name: Install dependencies
      shell: bash
      run: bun install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
