$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useGitignore: true
files:
  - '**'
  - .*
  - .*/**
  - '!.git/**'
ignorePaths:
  - pnpm-lock.yaml
dictionaries:
  - npm
  - softwareTerms
  - fullstack
  - html
  - css
  - redis
import:
  - '@cspell/dict-redis/cspell-ext.json'
words:
  - aceternity
  - airpods
  - anishde
  - antec
  - argb
  - asus
  - bentogrids
  - bradlc
  - cleanshot
  - cmdk
  - cobe
  - createcluster
  - createdb
  - createuser
  - customizer
  - dbaeumer
  - delba
  - dotenvx
  - dropcluster
  - eihab
  - fuma
  - fumadocs
  - ghostty
  - gifs
  - googleusercontent
  - hexpm
  - hiett
  - iina
  - innerhtml
  - jahir
  - joshwcomeau
  - karabiner
  - keka
  - keychron
  - keystyle
  - leerob
  - linktree
  - lokalise
  - macbook
  - maximeheckel
  - motrix
  - nelsonlai
  - nelsonlaidev
  - nerdfish
  - nextdotjs
  - nikolovlazar
  - nodedotjs
  - nohup
  - nosniff
  - noto
  - nums
  - nuqs
  - oliveira
  - orbstack
  - orpc
  - paralleldrive
  - planetscale
  - plpgsql
  - psql
  - radixui
  - reactquery
  - rebar
  - rmiz
  - ryzen
  - sameorigin
  - samuelkraft
  - shadcn
  - shiki
  - shikijs
  - simulately
  - sonarjs
  - techstack
  - theodorusclarence
  - timebombs
  - tsvector
  - turbopack
  - turborepo
  - umami
  - unifiedjs
  - unzoom
  - vocs
  - waka
  - wakatime
  - zenorocha
