version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: nelsonlaime-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nelsonlaime
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nelsonlaime-network
  redis:
    image: redis
    container_name: nelsonlaime-redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - nelsonlaime-network

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: nelsonlaime-redis-http
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: nelsonlaime
      SRH_CONNECTION_STRING: 'redis://redis:6379'
    networks:
      - nelsonlaime-network
    depends_on:
      - redis

volumes:
  db:
  redis:

networks:
  nelsonlaime-network:
    driver: bridge
