packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@posthog/cli'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - lefthook
  - sharp

patchedDependencies:
  next@16.0.0: patches/next@16.0.0.patch
