name: Generate changeset for Renovate

on:
  merge_group:
  pull_request_target:
    paths:
      - '.github/workflows/changesets-renovate.yml'
      - '**/pnpm-lock.yaml'
      - '**/package.json'

jobs:
  generate-changeset:
    name: Generate changeset
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.repository == 'tszhong0411/nelsonlai.me'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Run changesets-renovate
        run: pnpm dlx @scaleway/changesets-renovate
